include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - "**/*.g.dart"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    unused_import: error
    dead_code: warning
    missing_return: error
    missing_required_param: error
    invalid_assignment: error
    unused_local_variable: warning

linter:
  rules:
    # Estilo y convenciones
    always_declare_return_types: true
    annotate_overrides: true
    camel_case_types: true
    prefer_single_quotes: true
    use_key_in_widget_constructors: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    unnecessary_this: true
    avoid_unnecessary_containers: true
    use_build_context_synchronously: true
    prefer_const_constructors_in_immutables: true

    # Buenas prácticas y robustez
    avoid_empty_else: true
    avoid_returning_null: true
    await_only_futures: true
    close_sinks: true
    cancel_subscriptions: true
    unawaited_futures: true
    avoid_types_on_closure_parameters: true
    prefer_final_locals: true
    avoid_multiple_declarations_per_line: true
    prefer_expression_function_bodies: true
    avoid_init_to_null: true

    # Ajustes opcionales
    constant_identifier_names: false
    avoid_print: false
