name: rdg7
description: "Proyecto de gestion de reservas deportivas curso seminario de actualizacion 1041B"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.1.0  
  http: ^1.1.0
  flutter_bloc: ^8.1.3
  provider: ^6.1.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  http_mock_adapter: any
  test: any  
  mockito: ^5.4.4
  build_runner: ^2.4.7
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1


flutter_native_splash:
  color: "#ffffff" 
  image: assets/rdg7.png
  android: true
  ios: true
  web: true

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: assets/rdg7.png
  image_path: assets/rdg7.png
  remove_alpha_ios: true



flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/rdg7.png
